safe:        false
port: 4000
baseurl:
url: http://perktutor.github.io

source:      .
destination: ./_site
plugins_dir:     ./_plugins

future:      true
lsi:         false
permalink:   date

markdown:    kramdown
highlighter:    rouge

plugins:
  - jekyll-redirect-from

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highligher: rouge
